name: Publish yarn package

on:
  push:
    tags:
      - '*'
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          #registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - run: yarn install
      - run: yarn build
      - run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
